name: Bug Report
description: Report bugs with steps to reproduce, environment and severity.
type: bug
body:
    - type: textarea
      id: summary
      attributes:
          label: Summary
          description: Provide a brief summary of the bug
      validations:
          required: true
    - type: textarea
      id: steps
      attributes:
          label: Steps to reproduce
          description: Provide step-by-step reproduction instructions
          placeholder: |
              1. Go to ...
              2. Click ...
    - type: textarea
      id: expected
      attributes:
          label: Expected behavior
          description: Describe what you expected to happen
    - type: input
      id: url_ref
      attributes:
          label: Reference URL
          description: Link to the relevant page or resource where the bug was first observed
      validations:
          required: true
    - type: input
      id: url_dev
      attributes:
          label: DEV URL
          description: Link to the page where the bug has been replicated on DEV
    - type: dropdown
      id: device
      attributes:
          label: Device
          options:
              - PC
              - Mobile
              - Tablet
    - type: dropdown
      id: browser
      attributes:
          label: Browser
          options:
              - Chrome
              - Edge
              - Firefox
              - Safari
              - Other
    - type: textarea
      id: notes
      attributes:
          label: Notes / References / Media
          description: Links, references, media or anything else useful
    - type: dropdown
      id: priority
      attributes:
          label: Priority
          options:
              - Low
              - Moderate
              - Urgent
              - Critical
          default: 0
      validations:
          required: true
